defaultNamespace: default

helm:
  chart: "./chart"
  valuesFiles:
  - values.yaml

targetCustomizations:
- name: loadbalancer
  clusterSelector:
    matchLabels:
      demo-loadbalancer: enabled
  helm:
    values:
      config:
        loadbalancerEnabled: true